### ISSUE TITLE
SARIF log parsing issue (v.1.9.1)

### ISSUE THREAD

**Issue by jaspervdstraten** [microsoft/security-devops-azdevops#104]
So for clarity. Creating a new issue with reference to the old one here: [(https://github.com/microsoft/security-devops-azdevops/issues/86)]

Hi @chrisnielsen-MS, I am running into the same issue as described above with version 1.11.1

Analyze:  Running Terrascan 1.18.0.1 

Tool run time: 1.4032052 seconds
    ------------------------------------------------------------------------------
    Terrascan completed with exit code 5
    ------------------------------------------------------------------------------
    
  Process:
    Convert:
      Converting any raw tool logs to Sarif format ...
      Completed converting raw tool logs to Sarif format.
    Import:
##[error]JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.
##[error]MSDO CLI exited with an error exit code: 1
Finishing: Microsoft Security DevOps

**Comment by chrisnielsen-MS** [comment]
Thank you for reaching out @jaspervdstraten. We recently had a regression in the Microsoft.Security.DevOps.Cli package that caused it to be framework-dependent instead of self-contained, which could have led to this code using a different version of the parsing library than expected on some agents. To rule that out as a potential cause, can you confirm which version of the Microsoft.Security.DevOps.Cli package you are seeing this on? Versions above 0.201.0 have this fixed. You can find the version near the top of your task logs, in a log string like this:

Installed Microsoft.Security.Devops.Cli.win-x64 version 0.202.0

**Comment by jaspervdstraten** [comment]
Running 0.202.0 now.
Seems to be running fine again. Thanks for the response!

**Comment by chrisnielsen-MS** [comment]
Awesome, that confirms my theory and I'm glad it is back to working as intended!
