### ISSUE TITLE
task CredScan@2 Microsoft.Security.CredScan broken

### ISSUE THREAD

**Issue by quasarea** [microsoft/security-devops-azdevops#97]
Since morning we are observing issue with Microsoft CredScan task

Unfortunately task documentation has no link to any repo, only https://learn.microsoft.com/en-us/previous-versions/azure/security/develop/security-code-analysis-overview, perhaps article author @TerryLanfear could help?

```
Starting: CredScan
==============================================================================
Task         : Credential Scanner
Description  : Scan source code for committed credentials
Version      : 2.336.0
Author       : Microsoft Corporation
Help         : [Extension Docs](https://aka.ms/mscadocs)
==============================================================================
Enabling TLS 1.2...
Initializing analysis environment...
Downloaded nuget.exe: D:\a\_sdt\nuget.exe
"D:\a\_sdt\nuget.exe" install Microsoft.Security.CredScan -Source https://pkgs.dev.azure.com/secdevtools/_packaging/SecDevTools/nuget/v3/index.json -ConfigFile D:\a\_sdt\dt.nuget.config -NonInteractive
Feeds used:
  https://pkgs.dev.azure.com/secdevtools/_packaging/SecDevTools/nuget/v3/index.json

Installing package 'Microsoft.Security.CredScan' to 'D:\a\_sdt'.
Using credentials from config. UserName: VssSessionToken
Unable to load the service index for source https://pkgs.dev.azure.com/secdevtools/_packaging/SecDevTools/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by charlesoxyer** [comment]
Hello - MSCA is no longer supported and has been past end of life support since [March 2022](https://devblogs.microsoft.com/premier-developer/microsoft-security-code-analysis/). Customers can gain support of our latest tooling through [MSDO](https://learn.microsoft.com/en-us/azure/defender-for-cloud/azure-devops-extension) and [GitHub Advanced Security for AzDO](https://azure.microsoft.com/en-us/products/devops/github-advanced-security).
